from rl.agents.tabular.action_values_table import ActionValuesTable

from rl.agents.tabular.off_policy_monte_carlo import OffPolicyMonteCarloAgent
from rl.agents.tabular.on_policy_monte_carlo import OnPolicyMonteCarloAgent
